export const cardList = [
  {
    id: 1,
    theme: "orange",
    topic: "Web Design",
    title: "Название задачи",
    date: "30.10.23",
    status: "Без статуса",
  },
  {
    id: 2,
    theme: "green",
    topic: "Research",
    title: "Название задачи",
    date: "30.10.23",
    status: "Без статуса",
  },
  {
    id: 3,
    theme: "orange",
    topic: "Web Design",
    title: "Название задачи",
    date: "30.10.23",
    status: "Без статуса",
  },
  {
    id: 4,
    theme: "purple",
    topic: "Copywriting",
    title: "Название задачи",
    date: "30.10.23",
    status: "Без статуса",
  },
  {
    id: 5,
    theme: "orange",
    topic: "Web Design",
    title: "Название задачи",
    date: "30.10.23",
    status: "Без статуса",
  },
  {
    id: 6,
    theme: "green",
    topic: "Research",
    title: "Название задачи",
    date: "30.10.23",
    status: "Нужно сделать",
  },
  {
    id: 7,
    theme: "green",
    topic: "Research",
    title: "Название задачи",
    date: "30.10.23",
    status: "В работе",
  },
  {
    id: 8,
    theme: "purple",
    topic: "Copywriting",
    title: "Название задачи",
    date: "30.10.23",
    status: "В работе",
  },
  {
    id: 9,
    theme: "orange",
    topic: "Web Design",
    title: "Название задачи",
    date: "30.10.23",
    status: "В работе",
  },
  {
    id: 10,
    theme: "green",
    topic: "Research",
    title: "Название задачи",
    date: "30.10.23",
    status: "Тестирование",
  },
  {
    id: 11,
    theme: "green",
    topic: "Research",
    title: "Название задачи",
    date: "30.10.23",
    status: "Готово",
  },
];
